### ISSUE TITLE
Urgent: Transfer Paper from EMNLP to ICTAI

### ISSUE THREAD

**Issue by joshkyh** [SpectData/MONAH_Earnings_Call#10]
Objectives:
Transfer all content over from EMNLP to ICTAI. 

Ensuring that bibliography works and in-passage citations work.

Ensuring that the figures appear. Some are across two columns, some are contained within one column.

Ensuring that the equations appear.

Ensuring that you also brought the appendix over.

Don't worry about page gaps. I'll work on them this weekend.

Urgency:
By Friday 11am (Sydney time)

EMNLP Read link:
https://www.overleaf.com/read/pjqnbtqjjtqb

ICTAI Write link:
https://www.overleaf.com/4489352462rkjhtbqpsbvv

**Comment by mfmakahiya** [comment]
Hi Joshua! I have transferred all the elements from the original paper to IEEE format, and compiled it. In my quick glance, everything seems to be working perfectly. Can you check if the basic formatting looks fine on you? I didn't touch the positioning of the tables and figures yet. Although I edited one of the math symbols in one table, the "^" and replaced it with "**" temporarily since it returns an error when using ^. Thanks!

**Comment by joshkyh** [comment]
Thank you!
